# Gitee CI 配置
name: 构建和部署

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build

      - name: 部署到 Gitee Pages
        run: |
          echo "构建完成，静态文件已准备好"
